CREATE TABLE IF NOT EXISTS `academic_structures` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código único de la asignatura/plan',
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre de la asignatura o plan',
  `credits` int DEFAULT NULL COMMENT 'Número de créditos de la asignatura',
  `category` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'subject' COMMENT 'Tipo: asignatura, plan o módulo',
  `duration` int DEFAULT NULL COMMENT 'Semestre recomendado (1-10)',
  `level` int DEFAULT NULL,
  `acronym` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hours` int DEFAULT NULL COMMENT 'Horas académicas por semana',
  `is_active` tinyint(1) DEFAULT '1' COMMENT 'Si está activo en el sistema',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `course` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clplestud` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `school_code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `school_prog` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_bimestre` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `academic_structures_acronym_IDX` (`acronym`,`id_bimestre`) USING BTREE,
  KEY `idx_academic_structures_type` (`category`),
  KEY `idx_academic_structures_is_active` (`is_active`)
) ENGINE=InnoDB AUTO_INCREMENT=952 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;